-- Run in Supabase SQL editor (or psql).
-- Booking request queue for all services. Admin auth is handled by
-- NextAuth Google sign-in + ADMIN_EMAIL allowlist (see src/lib/admin.ts),
-- so there is no local admin_users table.

create table if not exists booking_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  slug text not null,
  slot timestamptz not null,
  duration_min integer not null,
  name text not null,
  email text not null,
  notes text,
  status text not null default 'pending' check (status in ('pending','approved','denied')),
  decided_at timestamptz,
  decided_by text
);

create index if not exists booking_requests_slot_idx on booking_requests (slot);
create index if not exists booking_requests_status_idx on booking_requests (status);

-- Only one pending/approved row per slot start. Denied rows free up automatically.
-- Cross-service overlap (e.g. a 30-min slot overlapping a 4-hour workshop) is
-- enforced in application code, not in the DB.
create unique index if not exists booking_requests_active_slot_idx
  on booking_requests (slot)
  where status in ('pending','approved');
