-- Bootstrap the public tables currently used by runtime routes.
-- Safe to run on a fresh project or alongside the earlier draft migration.

create table if not exists booking_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  slug text not null,
  slot timestamptz not null,
  duration_min integer not null,
  name text not null,
  email text not null,
  notes text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'denied')),
  decided_at timestamptz,
  decided_by text
);

create index if not exists booking_requests_slot_idx on booking_requests (slot);
create index if not exists booking_requests_status_idx on booking_requests (status);

create unique index if not exists booking_requests_active_slot_idx
  on booking_requests (slot)
  where status in ('pending', 'approved');

create table if not exists resource_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  resource_slug text not null,
  email text not null
);

create index if not exists resource_requests_resource_slug_idx on resource_requests (resource_slug);
create index if not exists resource_requests_email_idx on resource_requests (email);

create table if not exists bookings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  slug text not null,
  slot timestamptz not null,
  customer_email text not null,
  stripe_session_id text not null unique
);

create index if not exists bookings_slot_idx on bookings (slot);
create index if not exists bookings_customer_email_idx on bookings (customer_email);
